### ISSUE TITLE
/createの画像、プレビューされるように

### ISSUE THREAD

**Issue by whooolemilk** [traveli-dev/traveli-web#148]
![image](https://user-images.githubusercontent.com/74092547/181742201-ef34d7f8-0a1a-44e1-846e-02efb9d402df.png)
ここ

**Comment by Daaiki** [comment]
プレビューはされてるけど位置がわるいな

**Comment by Daaiki** [comment]
左上だけ見えてる感じっぽい

**Comment by whooolemilk** [comment]
わろた笑そゆことか笑
画像が悪かった笑
問題なさそうならクローズしてください笑

**Comment by Daaiki** [comment]
良い感じに最適化して表示させれるかどうかの検証はする！
