### ISSUE TITLE
認証後リダイレクト機能求む

### ISSUE THREAD

**Issue by sueCalystegia00** [traveli-dev/traveli-web#174]
# 😵共有したページが見られなくなる
恐らくログイン認証がされていない状態でindexページ以外にアクセスすると，強制的にindexに飛ばされる仕様となっている．
この状態で，ある未登録ユーザがTraveliでまとめたページにアクセスするのは不便．

# 🔍起きること
1. 新規ユーザ(未承認)が，共有されたTraveliページリンクにアクセスする(URLは https://traveli-web.vercel.app/{{旅行のID}} )
2. ログインしていないため強制的にindexページへリダイレクトする (URLは https://traveli-web.vercel.app )
3. ログイン認証し，homeページへ .....あれ，共有されたページは？
4. 再度，共有されたTraveliページリンクを叩き直す

...となる．

# 🖍提案
indexページにリダイレクトするのは良いとして，ログイン後は最初にアクセスしようとしたまとめページにリダイレクトしてほしい．

**Comment by Daaiki** [comment]
issue起票ありがとうございます！！  
その問題は認識していて、idページは認証なしでアクセス可能、未認証の場合は、編集不可、保存不可とするつもりです。  
保存ボタンを押すと、ログイン、ゲストログインのモーダルを出すように対応します！
